In [23]:
import sys
sys.path.append('/workspaces/quantum/')
from colors import Bcolors as bc

In [24]:
import numpy as np

# Load the training data
with open('../data/split-data/train.npy', 'rb') as f:
    train_input = np.load(f)
    train_labels = np.load(f)

# Load the testing data
with open('../data/split-data/test.npy', 'rb') as f:
    test_input = np.load(f)
    test_labels = np.load(f)

# Define Classifiers 🔮

## Random classifier 🪙

In [25]:
import random
random.seed(a=None, version=2)

def classify(passenger):
    return random.randint(0, 1)

## Death classifier 🪦

In [26]:
def predict_death(item):
    return 0

# Classification Runner 🏃‍♀️

In [27]:
def run(f_classify, x):
    return list(map(f_classify, x))

result = run(classify, train_input)

# Classifier Evaluation 📋

In [28]:
def evaluate(predictions, actual) -> str:
    correct = list(filter(
        lambda item: item[0] == item[1],
        list(zip(predictions, actual))
    ))
    
    return '{} correct predictions out of {}. Accuracy {:.0f} %' \
        .format(len(correct), len(actual), 100*len(correct)/len(actual))

In [29]:
print('🪙Random classifier:', evaluate(run(classify, train_input), train_labels))
print('🪦Death classifier: ', evaluate(run(predict_death, train_input), train_labels))

🪙Random classifier: 373 correct predictions out of 711. Accuracy 52 %
🪦Death classifier:  434 correct predictions out of 711. Accuracy 61 %


## Confusion matrix

In [30]:
from sklearn.metrics import confusion_matrix

uniform_predictions = run(classify, train_input)
uniform_cm = confusion_matrix(train_labels, uniform_predictions)
print('🪙 Uniform confusion matrix:\n', uniform_cm)

print()

death_predictions = run(predict_death, train_input)
death_cm = confusion_matrix(train_labels, death_predictions)
print('🪦 Death confusion matrix:\n', death_cm)

🪙 Uniform confusion matrix:
 [[204 230]
 [152 125]]

🪦 Death confusion matrix:
 [[434   0]
 [277   0]]


## Four scores from the confusion matrix
1. Precision score
2. Recall score
3. Specificity
4. Negative predictive value (NPV)

In [31]:
from sklearn.metrics import precision_score, recall_score

def specificity(matrix):
    return matrix[0][0]/(matrix[0][0]+matrix[0][1]) if (matrix[0][0]+matrix[0][1] > 0) else 0

def npv(matrix):
    return matrix[0][0]/(matrix[0][0]+matrix[1][0]) if (matrix[0][0]+matrix[1][0] > 0) else 0

In [32]:
def print_classifier_scores(train_labels, predictions, cm):  
    print('The precision score of the random classifier is {:.2f}'
        .format(precision_score(train_labels, predictions)))
    print('The recall score of the random classifier is {:.2f}'
        .format(recall_score(train_labels, predictions)))
    print('The specificity score of the random classifier is {:.2f}'
        .format(specificity(cm)))
    print('The npv score of the random classifier is {:.2f}'
    .   format(npv(cm)))

### 🪙 List the scores of the random classifier.

In [33]:
print(f'🪙 {bc.HEADER}Random classifier scores:{bc.ENDC}')
print_classifier_scores(train_labels, uniform_predictions, uniform_cm)
print()
print(f'🪙 {bc.HEADER}Random classifier confusion matrix:{bc.ENDC}\n', uniform_cm)

🪙 Random classifier scores:
The precision score of the random classifier is 0.35
The recall score of the random classifier is 0.45
The specificity score of the random classifier is 0.47
The npv score of the random classifier is 0.57

🪙 Random classifier confusion matrix:
 [[204 230]
 [152 125]]


### 🪦 List the scores of the death classifier.

In [34]:
print(f'🪦 {bc.HEADER}Death classifier scores:{bc.ENDC}')
print_classifier_scores(train_labels, death_predictions, death_cm)
print()
print(f'🪦 {bc.HEADER}Death classifier confusion matrix:{bc.ENDC}\n', death_cm)

🪦 Death classifier scores:
The precision score of the random classifier is 0.00
The recall score of the random classifier is 0.00
The specificity score of the random classifier is 1.00
The npv score of the random classifier is 0.61

🪦 Death classifier confusion matrix:
 [[434   0]
 [277   0]]


/workspaces/quantum/venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


### 😈 List the scores of the hypocrite classifier.

Define a hypocrite classifier.

In [35]:
# Listing A hypocrite classifier
def hypocrite(passenger, weight):
    return round(min(1,max(0,weight*0.5+random.uniform(0, 1))))

Obtain scores.

In [36]:
# Listing The scores of the hypocrite classifier
hypocrite_predictions = run(lambda passenger: hypocrite(passenger, -0.5), train_input)
hypocrite_cm = confusion_matrix(train_labels, hypocrite_predictions)

print(f'😈 {bc.HEADER}Hypocrite classifier scores:{bc.ENDC}')
print_classifier_scores(train_labels, hypocrite_predictions, hypocrite_cm)
print()
print(f'😈 {bc.HEADER}Hypocrite classifier confusion matrix:{bc.ENDC}\n', hypocrite_cm)

😈 Hypocrite classifier scores:
The precision score of the random classifier is 0.36
The recall score of the random classifier is 0.25
The specificity score of the random classifier is 0.72
The npv score of the random classifier is 0.60

😈 Hypocrite classifier confusion matrix:
 [[311 123]
 [208  69]]
